name: Terraform EKS Cluster Creation

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:
jobs:
  terraform:
    runs-on: ullagallu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Init (EKS)
      working-directory: ./eks-daily
      run: terraform init

    - name: Terraform Validate (EKS)
      working-directory: ./eks-daily
      run: terraform validate

    - name: Terraform Plan (EKS)
      working-directory: ./eks-daily
      run: terraform plan

    - name: Terraform Apply (EKS)
      working-directory: ./eks-daily
      run: terraform apply -auto-approve

