name: Terraform EKS Cluster Deletion

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ullagallu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Init (EKS)
      working-directory: ./eks-daily
      run: terraform init

    - name: Terraform Destroy (EKS)
      working-directory: ./eks-daily
      run: terraform destroy