name: EKS-MY-PRACTICE CREATION

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  terraform:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Init (EKS)
      working-directory: ./eks-my-practice
      run: terraform init

    - name: Terraform Validate (EKS)
      working-directory: ./eks-my-practice
      run: terraform validate

    - name: Terraform Plan (EKS)
      working-directory: ./eks-my-practice
      run: terraform plan

    - name: Terraform Apply (EKS)
      working-directory: ./eks-my-practice
      run: terraform apply -auto-approve

