name: Terraform EKS Cluster Deletion

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ullagallu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch'
      run: terraform destroy -auto-approve
